-- Execute este arquivo no SQL Editor do seu projeto Supabase.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 80),
  handle text not null unique check (handle ~ '^[A-Za-z0-9_]+$'),
  avatar_url text,
  bio text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "Perfis públicos podem ser lidos" on public.profiles;
drop policy if exists "Usuários podem criar o próprio perfil" on public.profiles;
drop policy if exists "Usuários podem editar o próprio perfil" on public.profiles;

create policy "Perfis públicos podem ser lidos"
  on public.profiles for select using (true);
create policy "Usuários podem criar o próprio perfil"
  on public.profiles for insert with check (auth.uid() = id);
create policy "Usuários podem editar o próprio perfil"
  on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name, handle)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', 'Pessoa possível'),
    lower(coalesce(new.raw_user_meta_data ->> 'handle', 'usuario_' || substr(new.id::text, 1, 8)))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

insert into public.profiles (id, name, handle)
select
  u.id,
  coalesce(u.raw_user_meta_data ->> 'name', 'Pessoa possível'),
  lower(coalesce(u.raw_user_meta_data ->> 'handle', 'usuario_' || substr(u.id::text, 1, 8)))
from auth.users as u
on conflict (id) do nothing;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 5000),
  kind text not null default 'Post',
  media_url text,
  media_type text,
  created_at timestamptz not null default now()
);

alter table public.posts add column if not exists media_url text;
alter table public.posts add column if not exists media_type text;

create table if not exists public.post_likes (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

alter table public.posts enable row level security;
alter table public.post_likes enable row level security;
alter table public.comments enable row level security;

drop policy if exists "Posts públicos podem ser lidos" on public.posts;
drop policy if exists "Usuários podem criar posts" on public.posts;
drop policy if exists "Autores podem editar posts" on public.posts;
drop policy if exists "Autores podem apagar posts" on public.posts;
drop policy if exists "Curtidas podem ser lidas" on public.post_likes;
drop policy if exists "Usuários podem curtir" on public.post_likes;
drop policy if exists "Usuários podem remover a própria curtida" on public.post_likes;
drop policy if exists "Comentários públicos podem ser lidos" on public.comments;
drop policy if exists "Usuários podem comentar" on public.comments;
drop policy if exists "Autores podem apagar comentários" on public.comments;

create policy "Posts públicos podem ser lidos" on public.posts for select using (true);
create policy "Usuários podem criar posts" on public.posts for insert with check (auth.uid() = author_id);
create policy "Autores podem editar posts" on public.posts for update using (auth.uid() = author_id) with check (auth.uid() = author_id);
create policy "Autores podem apagar posts" on public.posts for delete using (auth.uid() = author_id);
create policy "Curtidas podem ser lidas" on public.post_likes for select using (true);
create policy "Usuários podem curtir" on public.post_likes for insert with check (auth.uid() = user_id);
create policy "Usuários podem remover a própria curtida" on public.post_likes for delete using (auth.uid() = user_id);
create policy "Comentários públicos podem ser lidos" on public.comments for select using (true);
create policy "Usuários podem comentar" on public.comments for insert with check (auth.uid() = author_id);
create policy "Autores podem apagar comentários" on public.comments for delete using (auth.uid() = author_id);

insert into storage.buckets (id, name, public)
values ('posts-media', 'posts-media', true)
on conflict (id) do update set public = true;

drop policy if exists "Mídias públicas podem ser lidas" on storage.objects;
drop policy if exists "Usuários podem enviar suas mídias" on storage.objects;
drop policy if exists "Usuários podem atualizar suas mídias" on storage.objects;
drop policy if exists "Usuários podem apagar suas mídias" on storage.objects;

create policy "Mídias públicas podem ser lidas"
  on storage.objects for select using (bucket_id = 'posts-media');
create policy "Usuários podem enviar suas mídias"
  on storage.objects for insert with check (bucket_id = 'posts-media' and auth.uid()::text = (storage.foldername(name))[1]);
create policy "Usuários podem atualizar suas mídias"
  on storage.objects for update using (bucket_id = 'posts-media' and auth.uid()::text = (storage.foldername(name))[1]);
create policy "Usuários podem apagar suas mídias"
  on storage.objects for delete using (bucket_id = 'posts-media' and auth.uid()::text = (storage.foldername(name))[1]);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now(),
  read_at timestamptz
);

alter table public.messages enable row level security;
drop policy if exists "Usuários podem ler suas mensagens" on public.messages;
drop policy if exists "Usuários podem enviar mensagens" on public.messages;
drop policy if exists "Destinatários podem marcar como lida" on public.messages;
create policy "Usuários podem ler suas mensagens" on public.messages for select using (auth.uid() = sender_id or auth.uid() = receiver_id);
create policy "Usuários podem enviar mensagens" on public.messages for insert with check (auth.uid() = sender_id);
create policy "Destinatários podem marcar como lida" on public.messages for update using (auth.uid() = receiver_id) with check (auth.uid() = receiver_id);

do $$
begin
  alter publication supabase_realtime add table public.messages;
exception when duplicate_object then
  null;
end $$;

create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(title) between 2 and 100),
  description text not null default '' check (char_length(description) <= 2000),
  listing_type text not null check (listing_type in ('venda', 'troca')),
  price numeric(10,2) check (price is null or price >= 0),
  location text not null check (char_length(location) between 2 and 120),
  status text not null default 'active' check (status in ('active', 'paused', 'sold', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.listings enable row level security;
drop policy if exists "Anúncios ativos podem ser lidos" on public.listings;
drop policy if exists "Usuários podem criar anúncios" on public.listings;
drop policy if exists "Vendedores podem editar anúncios" on public.listings;
drop policy if exists "Vendedores podem remover anúncios" on public.listings;
create policy "Anúncios ativos podem ser lidos" on public.listings for select using (status = 'active' or auth.uid() = seller_id);
create policy "Usuários podem criar anúncios" on public.listings for insert with check (auth.uid() = seller_id);
create policy "Vendedores podem editar anúncios" on public.listings for update using (auth.uid() = seller_id) with check (auth.uid() = seller_id);
create policy "Vendedores podem remover anúncios" on public.listings for delete using (auth.uid() = seller_id);

drop trigger if exists listings_updated_at on public.listings;
create trigger listings_updated_at
before update on public.listings
for each row execute procedure public.set_updated_at();

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  payer_id uuid not null references public.profiles(id) on delete cascade,
  listing_id bigint references public.listings(id) on delete set null,
  kind text not null check (kind in ('purchase', 'donation')),
  amount numeric(10,2) not null check (amount >= 1),
  provider text not null check (provider in ('pix', 'mercadopago', 'stripe')),
  purpose text not null default '',
  status text not null default 'pending' check (status in ('pending', 'paid', 'failed', 'refunded')),
  provider_reference text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.payments enable row level security;
drop policy if exists "Usuários podem ver seus pagamentos" on public.payments;
drop policy if exists "Usuários podem criar seus pagamentos" on public.payments;
drop policy if exists "Usuários não alteram status do pagamento" on public.payments;
create policy "Usuários podem ver seus pagamentos" on public.payments for select using (auth.uid() = payer_id);
create policy "Usuários podem criar seus pagamentos" on public.payments for insert with check (auth.uid() = payer_id);
create policy "Usuários não alteram status do pagamento" on public.payments for update using (false);

drop trigger if exists payments_updated_at on public.payments;
create trigger payments_updated_at
before update on public.payments
for each row execute procedure public.set_updated_at();

create table if not exists public.call_sessions (
  id uuid primary key default gen_random_uuid(),
  host_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null check (provider in ('livekit', 'daily')),
  room_name text not null unique,
  mode text not null check (mode in ('audio', 'video')),
  status text not null default 'active' check (status in ('active', 'ended')),
  created_at timestamptz not null default now(),
  ended_at timestamptz
);

alter table public.call_sessions enable row level security;
drop policy if exists "Chamadas ativas podem ser vistas" on public.call_sessions;
drop policy if exists "Usuários podem criar chamadas" on public.call_sessions;
drop policy if exists "Criadores podem encerrar chamadas" on public.call_sessions;
create policy "Chamadas ativas podem ser vistas" on public.call_sessions for select using (status = 'active' or auth.uid() = host_id);
create policy "Usuários podem criar chamadas" on public.call_sessions for insert with check (auth.uid() = host_id);
create policy "Criadores podem encerrar chamadas" on public.call_sessions for update using (auth.uid() = host_id) with check (auth.uid() = host_id);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  post_id bigint references public.posts(id) on delete set null,
  reason text not null check (reason in ('spam', 'harassment', 'violence', 'illegal', 'other')),
  details text not null default '' check (char_length(details) <= 2000),
  status text not null default 'pending' check (status in ('pending', 'reviewing', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

alter table public.reports enable row level security;
drop policy if exists "Usuários podem criar denúncias" on public.reports;
drop policy if exists "Usuários podem ver suas denúncias" on public.reports;
create policy "Usuários podem criar denúncias" on public.reports for insert with check (auth.uid() = reporter_id);
create policy "Usuários podem ver suas denúncias" on public.reports for select using (auth.uid() = reporter_id);
