-- Possível — schema completo e idempotente.
-- Execute este arquivo inteiro no SQL Editor do Supabase.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 80),
  handle text not null unique check (handle ~ '^[a-z0-9_]+$'),
  avatar_url text,
  bio text not null default '' check (char_length(bio) <= 500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  candidate text;
begin
  candidate := lower(regexp_replace(coalesce(new.raw_user_meta_data ->> 'handle', ''), '[^a-zA-Z0-9_]', '', 'g'));
  if candidate = '' then
    candidate := 'usuario_' || substr(new.id::text, 1, 8);
  end if;
  if exists(select 1 from public.profiles where handle = candidate) then
    candidate := left(candidate, 22) || '_' || substr(new.id::text, 1, 6);
  end if;

  insert into public.profiles (id, name, handle)
  values (
    new.id,
    left(coalesce(nullif(trim(new.raw_user_meta_data ->> 'name'), ''), 'Pessoa possível'), 80),
    candidate
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

insert into public.profiles (id, name, handle)
select
  u.id,
  left(coalesce(nullif(trim(u.raw_user_meta_data ->> 'name'), ''), 'Pessoa possível'), 80),
  'usuario_' || substr(u.id::text, 1, 8)
from auth.users u
where not exists(select 1 from public.profiles p where p.id = u.id)
on conflict do nothing;

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 5000),
  kind text not null default 'Post' check (kind in ('Post','Foto','Vídeo','Doação','Projeto')),
  media_url text,
  media_type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.posts add column if not exists updated_at timestamptz not null default now();
drop trigger if exists posts_updated_at on public.posts;
create trigger posts_updated_at before update on public.posts
for each row execute function public.set_updated_at();

create table if not exists public.post_likes (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.comments add column if not exists updated_at timestamptz not null default now();
drop trigger if exists comments_updated_at on public.comments;
create trigger comments_updated_at before update on public.comments
for each row execute function public.set_updated_at();

create table if not exists public.follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  check (follower_id <> following_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now(),
  read_at timestamptz,
  check (sender_id <> receiver_id)
);

create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(title) between 2 and 100),
  description text not null default '' check (char_length(description) <= 2000),
  listing_type text not null check (listing_type in ('venda','troca','doacao')),
  price numeric(10,2) check (price is null or price >= 0),
  location text not null check (char_length(location) between 2 and 120),
  image_url text,
  category text,
  images text[] not null default '{}',
  status text not null default 'active' check (status in ('active','reserved','completed','paused','sold','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.listings add column if not exists image_url text;
alter table public.listings add column if not exists category text;
alter table public.listings add column if not exists images text[] not null default '{}';
alter table public.listings drop constraint if exists listings_listing_type_check;
alter table public.listings add constraint listings_listing_type_check check (listing_type in ('venda','troca','doacao'));
alter table public.listings drop constraint if exists listings_status_check;
alter table public.listings add constraint listings_status_check check (status in ('active','reserved','completed','paused','sold','closed'));
drop trigger if exists listings_updated_at on public.listings;
create trigger listings_updated_at before update on public.listings
for each row execute function public.set_updated_at();

create table if not exists public.causes (
  id bigint generated by default as identity primary key,
  creator_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(title) between 3 and 120),
  description text not null check (char_length(description) between 10 and 3000),
  goal_amount numeric(12,2) not null check (goal_amount >= 1),
  raised_amount numeric(12,2) not null default 0 check (raised_amount >= 0),
  support_count integer not null default 0 check (support_count >= 0),
  image_url text,
  status text not null default 'active' check (status in ('active','completed','paused','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists causes_updated_at on public.causes;
create trigger causes_updated_at before update on public.causes
for each row execute function public.set_updated_at();

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  payer_id uuid not null references public.profiles(id) on delete cascade,
  listing_id bigint references public.listings(id) on delete set null,
  cause_id bigint references public.causes(id) on delete set null,
  kind text not null check (kind in ('purchase','donation','subscription')),
  amount numeric(10,2) not null check (amount >= 1),
  provider text not null check (provider in ('pix','mercadopago','stripe')),
  purpose text not null default '',
  status text not null default 'pending' check (status in ('pending','paid','failed','refunded')),
  provider_reference text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.payments add column if not exists cause_id bigint references public.causes(id) on delete set null;
alter table public.payments drop constraint if exists payments_kind_check;
alter table public.payments add constraint payments_kind_check check (kind in ('purchase','donation','subscription'));
drop trigger if exists payments_updated_at on public.payments;
create trigger payments_updated_at before update on public.payments
for each row execute function public.set_updated_at();

create or replace function public.update_cause_totals()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.cause_id is not null and new.status = 'paid' and (tg_op = 'INSERT' or old.status is distinct from 'paid') then
    update public.causes
    set raised_amount = raised_amount + new.amount,
        support_count = support_count + 1
    where id = new.cause_id;
  elsif tg_op = 'UPDATE' and old.cause_id is not null and old.status = 'paid' and new.status in ('refunded','failed') then
    update public.causes
    set raised_amount = greatest(0, raised_amount - old.amount),
        support_count = greatest(0, support_count - 1)
    where id = old.cause_id;
  end if;
  return new;
end;
$$;
drop trigger if exists payment_updates_cause on public.payments;
create trigger payment_updates_cause after insert or update of status on public.payments
for each row execute function public.update_cause_totals();

create table if not exists public.call_sessions (
  id uuid primary key default gen_random_uuid(),
  host_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid references public.profiles(id) on delete set null,
  provider text not null check (provider in ('livekit','daily')),
  room_name text not null unique,
  mode text not null check (mode in ('audio','video')),
  status text not null default 'active' check (status in ('active','ended')),
  created_at timestamptz not null default now(),
  ended_at timestamptz
);
alter table public.call_sessions add column if not exists recipient_id uuid references public.profiles(id) on delete set null;

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  post_id bigint references public.posts(id) on delete set null,
  reason text not null check (reason in ('spam','harassment','violence','illegal','other')),
  details text not null default '' check (char_length(details) <= 2000),
  status text not null default 'pending' check (status in ('pending','reviewing','resolved','dismissed')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  type text not null check (type in ('follow','like','comment','message','payment','system')),
  title text not null,
  body text not null default '',
  link text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.user_blocks (
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  plan text not null check (plan in ('free','pro')),
  status text not null check (status in ('pending','active','past_due','grace_period','canceled','expired')),
  provider text not null default 'mercadopago',
  provider_customer_id text,
  provider_subscription_id text unique,
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists subscriptions_updated_at on public.subscriptions;
create trigger subscriptions_updated_at before update on public.subscriptions
for each row execute function public.set_updated_at();

create table if not exists public.plan_entitlements (
  id bigint generated by default as identity primary key,
  plan text not null check (plan in ('free','pro')),
  feature_key text not null,
  enabled boolean not null default true,
  numeric_limit numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(plan, feature_key)
);

create table if not exists public.usage_counters (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  feature_key text not null,
  period text not null,
  usage numeric not null default 0,
  updated_at timestamptz not null default now(),
  unique(user_id, feature_key, period)
);

create table if not exists public.payment_webhook_events (
  id uuid primary key default gen_random_uuid(),
  provider text not null,
  event_id text not null,
  event_type text not null,
  payload jsonb not null,
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  unique(provider, event_id)
);

create table if not exists public.feature_audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  feature_key text not null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.plan_entitlements(plan,feature_key,enabled,numeric_limit) values
('free','active_listings',true,5),
('pro','active_listings',true,50),
('free','storage_gb',true,1),
('pro','storage_gb',true,10),
('free','call_participants',true,4),
('pro','call_participants',true,12),
('free','call_duration_minutes',true,30),
('pro','call_duration_minutes',true,120),
('free','advanced_stats',false,null),
('pro','advanced_stats',true,null),
('free','scheduled_posts',false,null),
('pro','scheduled_posts',true,null),
('free','saved_searches',false,null),
('pro','saved_searches',true,null),
('free','customization',false,null),
('pro','customization',true,null),
('free','pro_badge',false,null),
('pro','pro_badge',true,null)
on conflict(plan,feature_key) do update set enabled=excluded.enabled,numeric_limit=excluded.numeric_limit;

create or replace function public.get_effective_plan(p_user_id uuid default auth.uid())
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((
    select plan from public.subscriptions
    where user_id = coalesce(p_user_id, auth.uid())
      and status in ('active','grace_period')
      and (current_period_end is null or current_period_end > now())
    order by created_at desc
    limit 1
  ), 'free');
$$;

create or replace function public.can_use_feature(p_user_id uuid, p_feature_key text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select enabled from public.plan_entitlements
    where plan = public.get_effective_plan(p_user_id) and feature_key = p_feature_key), false);
$$;

create or replace function public.get_user_entitlements(p_user_id uuid default auth.uid())
returns table(feature_key text, enabled boolean, numeric_limit numeric)
language sql
stable
security definer
set search_path = public
as $$
  select pe.feature_key, pe.enabled, pe.numeric_limit
  from public.plan_entitlements pe
  where pe.plan = public.get_effective_plan(coalesce(p_user_id, auth.uid()));
$$;

create or replace function public.check_plan_limit(p_user_id uuid, p_feature_key text)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_limit numeric;
  v_usage numeric;
begin
  select numeric_limit into v_limit
  from public.plan_entitlements
  where plan = public.get_effective_plan(p_user_id) and feature_key = p_feature_key;
  if v_limit is null then return public.can_use_feature(p_user_id, p_feature_key); end if;
  if p_feature_key = 'active_listings' then
    select count(*) into v_usage from public.listings where seller_id = p_user_id and status = 'active';
  else
    select coalesce(sum(usage),0) into v_usage from public.usage_counters where user_id = p_user_id and feature_key = p_feature_key;
  end if;
  return v_usage < v_limit;
end;
$$;

create index if not exists posts_created_at_idx on public.posts(created_at desc);
create index if not exists comments_post_idx on public.comments(post_id, created_at);
create index if not exists messages_pair_idx on public.messages(sender_id, receiver_id, created_at);
create index if not exists listings_status_created_idx on public.listings(status, created_at desc);
create index if not exists causes_status_created_idx on public.causes(status, created_at desc);
create index if not exists notifications_user_created_idx on public.notifications(user_id, created_at desc);
create index if not exists subscriptions_user_status_idx on public.subscriptions(user_id, status);

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.post_likes enable row level security;
alter table public.comments enable row level security;
alter table public.follows enable row level security;
alter table public.messages enable row level security;
alter table public.listings enable row level security;
alter table public.causes enable row level security;
alter table public.payments enable row level security;
alter table public.call_sessions enable row level security;
alter table public.reports enable row level security;
alter table public.notifications enable row level security;
alter table public.user_blocks enable row level security;
alter table public.subscriptions enable row level security;
alter table public.plan_entitlements enable row level security;
alter table public.usage_counters enable row level security;
alter table public.payment_webhook_events enable row level security;
alter table public.feature_audit_logs enable row level security;

do $$
declare r record;
begin
  for r in select schemaname, tablename, policyname from pg_policies
    where schemaname='public' and tablename in (
      'profiles','posts','post_likes','comments','follows','messages','listings','causes','payments','call_sessions','reports','notifications','user_blocks','subscriptions','plan_entitlements','usage_counters'
    )
  loop
    execute format('drop policy if exists %I on %I.%I', r.policyname, r.schemaname, r.tablename);
  end loop;
end $$;

create policy "profiles_select" on public.profiles for select using (true);
create policy "profiles_insert_own" on public.profiles for insert with check (auth.uid() = id);
create policy "profiles_update_own" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "profiles_delete_own" on public.profiles for delete using (auth.uid() = id);

create policy "posts_select" on public.posts for select using (true);
create policy "posts_insert_own" on public.posts for insert with check (auth.uid() = author_id);
create policy "posts_update_own" on public.posts for update using (auth.uid() = author_id) with check (auth.uid() = author_id);
create policy "posts_delete_own" on public.posts for delete using (auth.uid() = author_id);

create policy "likes_select" on public.post_likes for select using (true);
create policy "likes_insert_own" on public.post_likes for insert with check (auth.uid() = user_id);
create policy "likes_delete_own" on public.post_likes for delete using (auth.uid() = user_id);

create policy "comments_select" on public.comments for select using (true);
create policy "comments_insert_own" on public.comments for insert with check (auth.uid() = author_id);
create policy "comments_update_own" on public.comments for update using (auth.uid() = author_id) with check (auth.uid() = author_id);
create policy "comments_delete_own" on public.comments for delete using (auth.uid() = author_id);

create policy "follows_select" on public.follows for select using (true);
create policy "follows_insert_own" on public.follows for insert with check (auth.uid() = follower_id);
create policy "follows_delete_own" on public.follows for delete using (auth.uid() = follower_id);

create policy "messages_select_participants" on public.messages for select using (auth.uid() in (sender_id, receiver_id));
create policy "messages_insert_sender" on public.messages for insert with check (auth.uid() = sender_id);
create policy "messages_update_receiver" on public.messages for update using (auth.uid() = receiver_id) with check (auth.uid() = receiver_id);
create policy "messages_delete_sender" on public.messages for delete using (auth.uid() = sender_id);

create policy "listings_select" on public.listings for select using (status = 'active' or auth.uid() = seller_id);
create policy "listings_insert_own" on public.listings for insert with check (auth.uid() = seller_id);
create policy "listings_update_own" on public.listings for update using (auth.uid() = seller_id) with check (auth.uid() = seller_id);
create policy "listings_delete_own" on public.listings for delete using (auth.uid() = seller_id);

create policy "causes_select" on public.causes for select using (status = 'active' or auth.uid() = creator_id);
create policy "causes_insert_own" on public.causes for insert with check (auth.uid() = creator_id);
create policy "causes_update_own" on public.causes for update using (auth.uid() = creator_id) with check (auth.uid() = creator_id);
create policy "causes_delete_own" on public.causes for delete using (auth.uid() = creator_id);

create policy "payments_select_own" on public.payments for select using (auth.uid() = payer_id);
create policy "payments_insert_own" on public.payments for insert with check (auth.uid() = payer_id and status = 'pending');

create policy "calls_select_participants" on public.call_sessions for select using (auth.uid() in (host_id, recipient_id));
create policy "calls_insert_host" on public.call_sessions for insert with check (auth.uid() = host_id);
create policy "calls_update_host" on public.call_sessions for update using (auth.uid() = host_id) with check (auth.uid() = host_id);

create policy "reports_insert_own" on public.reports for insert with check (auth.uid() = reporter_id);
create policy "reports_select_own" on public.reports for select using (auth.uid() = reporter_id);

create policy "notifications_select_own" on public.notifications for select using (auth.uid() = user_id);
create policy "notifications_update_own" on public.notifications for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "notifications_delete_own" on public.notifications for delete using (auth.uid() = user_id);

create policy "blocks_select_own" on public.user_blocks for select using (auth.uid() = blocker_id);
create policy "blocks_insert_own" on public.user_blocks for insert with check (auth.uid() = blocker_id);
create policy "blocks_delete_own" on public.user_blocks for delete using (auth.uid() = blocker_id);

create policy "subscriptions_select_own" on public.subscriptions for select using (auth.uid() = user_id);
create policy "entitlements_select_authenticated" on public.plan_entitlements for select using (auth.role() = 'authenticated');
create policy "usage_select_own" on public.usage_counters for select using (auth.uid() = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('posts-media','posts-media',true,104857600,array['image/jpeg','image/png','image/webp','video/mp4','video/webm'])
on conflict (id) do update set public=true,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "media_select" on storage.objects;
drop policy if exists "media_insert_own" on storage.objects;
drop policy if exists "media_update_own" on storage.objects;
drop policy if exists "media_delete_own" on storage.objects;
drop policy if exists "Mídias públicas podem ser lidas" on storage.objects;
drop policy if exists "Usuários podem enviar suas mídias" on storage.objects;
drop policy if exists "Usuários podem atualizar suas mídias" on storage.objects;
drop policy if exists "Usuários podem apagar suas mídias" on storage.objects;
create policy "media_select" on storage.objects for select using (bucket_id='posts-media');
create policy "media_insert_own" on storage.objects for insert with check (bucket_id='posts-media' and auth.uid()::text=(storage.foldername(name))[1]);
create policy "media_update_own" on storage.objects for update using (bucket_id='posts-media' and auth.uid()::text=(storage.foldername(name))[1]) with check (bucket_id='posts-media' and auth.uid()::text=(storage.foldername(name))[1]);
create policy "media_delete_own" on storage.objects for delete using (bucket_id='posts-media' and auth.uid()::text=(storage.foldername(name))[1]);

create or replace function public.notify_follow()
returns trigger language plpgsql security definer set search_path=public as $$
declare actor_name text;
begin
  select name into actor_name from public.profiles where id=new.follower_id;
  insert into public.notifications(user_id,actor_id,type,title,body,link)
  values(new.following_id,new.follower_id,'follow','Nova conexão',coalesce(actor_name,'Alguém') || ' começou a seguir você.','#connections');
  return new;
end $$;

drop trigger if exists follows_notify on public.follows;
create trigger follows_notify after insert on public.follows for each row execute function public.notify_follow();

create or replace function public.notify_like()
returns trigger language plpgsql security definer set search_path=public as $$
declare owner_id uuid; actor_name text;
begin
  select author_id into owner_id from public.posts where id=new.post_id;
  if owner_id is null or owner_id=new.user_id then return new; end if;
  select name into actor_name from public.profiles where id=new.user_id;
  insert into public.notifications(user_id,actor_id,type,title,body,link)
  values(owner_id,new.user_id,'like','Nova curtida',coalesce(actor_name,'Alguém') || ' curtiu sua publicação.','#inicio');
  return new;
end $$;

drop trigger if exists likes_notify on public.post_likes;
create trigger likes_notify after insert on public.post_likes for each row execute function public.notify_like();

create or replace function public.notify_comment()
returns trigger language plpgsql security definer set search_path=public as $$
declare owner_id uuid; actor_name text;
begin
  select author_id into owner_id from public.posts where id=new.post_id;
  if owner_id is null or owner_id=new.author_id then return new; end if;
  select name into actor_name from public.profiles where id=new.author_id;
  insert into public.notifications(user_id,actor_id,type,title,body,link)
  values(owner_id,new.author_id,'comment','Novo comentário',coalesce(actor_name,'Alguém') || ' comentou sua publicação.','#inicio');
  return new;
end $$;

drop trigger if exists comments_notify on public.comments;
create trigger comments_notify after insert on public.comments for each row execute function public.notify_comment();

create or replace function public.notify_message()
returns trigger language plpgsql security definer set search_path=public as $$
declare actor_name text;
begin
  select name into actor_name from public.profiles where id=new.sender_id;
  insert into public.notifications(user_id,actor_id,type,title,body,link)
  values(new.receiver_id,new.sender_id,'message','Nova mensagem',coalesce(actor_name,'Alguém') || ' enviou uma mensagem.','#messages');
  return new;
end $$;

drop trigger if exists messages_notify on public.messages;
create trigger messages_notify after insert on public.messages for each row execute function public.notify_message();

do $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='messages') then
    alter publication supabase_realtime add table public.messages;
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='notifications') then
    alter publication supabase_realtime add table public.notifications;
  end if;
end $$;
