const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const safeJSON=(raw,fallback)=>{try{return JSON.parse(raw)}catch{return fallback}};
const store={get:(k,f)=>safeJSON(localStorage.getItem(k),f),set:(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}}};
const toast=msg=>{const el=$('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2200)};
async function copy(text){try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text)}else{const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}toast('Copiado para a área de transferência.')}catch{toast('Não foi possível copiar automaticamente.')}}
const download=(href,name)=>{const a=document.createElement('a');a.href=href;a.download=name;document.body.appendChild(a);a.click();a.remove()};
const field=(label,id,type='text',value='',extra='')=>`<div class="field"><label for="${id}">${label}</label><input id="${id}" type="${type}" value="${value}" ${extra}></div>`;

const tools=[
{id:'juros',icon:'📈',name:'Juros Compostos',tag:'Finanças',desc:'Projete patrimônio, aportes e crescimento ao longo do tempo.'},
{id:'orcamento',icon:'💰',name:'Orçamento Pessoal',tag:'Finanças',desc:'Organize receitas e despesas e descubra sua sobra mensal.'},
{id:'curriculo',icon:'📄',name:'Currículo Rápido',tag:'Carreira',desc:'Monte um currículo limpo e pronto para imprimir em minutos.'},
{id:'qr',icon:'▦',name:'QR Code Pro',tag:'Marketing',desc:'Transforme links, textos e contatos em QR Codes baixáveis.'},
{id:'whatsapp',icon:'💬',name:'Link para WhatsApp',tag:'Vendas',desc:'Crie links com mensagem pronta para atendimento e campanhas.'},
{id:'utm',icon:'🔗',name:'Construtor de UTM',tag:'Marketing',desc:'Adicione rastreamento profissional aos links de campanha.'},
{id:'senha',icon:'🔐',name:'Gerador de Senhas',tag:'Segurança',desc:'Gere senhas fortes localmente sem enviar dados para servidores.'},
{id:'pomodoro',icon:'⏱️',name:'Pomodoro Focus',tag:'Produtividade',desc:'Cronômetro de foco com ciclos, pausas e contagem de sessões.'},
{id:'tarefas',icon:'✅',name:'Planejador de Tarefas',tag:'Produtividade',desc:'Registre prioridades e acompanhe tarefas salvas no dispositivo.'},
{id:'imagem',icon:'🖼️',name:'Conversor de Imagem',tag:'Utilidade',desc:'Converta imagens para PNG, JPEG ou WebP direto no navegador.'}
];

function renderGrid(filter=''){
 const q=filter.trim().toLowerCase();
 const items=tools.filter(t=>`${t.name} ${t.tag} ${t.desc}`.toLowerCase().includes(q));
 $('#toolGrid').innerHTML=items.map(t=>`<article class="tool-card"><span class="tool-icon">${t.icon}</span><h3>${t.name}</h3><p>${t.desc}</p><div class="tool-meta"><span>${t.tag}</span><button type="button" data-open="${t.id}">Abrir →</button></div></article>`).join('')||'<p>Nenhuma ferramenta encontrada.</p>';
 $$('[data-open]').forEach(b=>b.onclick=()=>openTool(b.dataset.open));
}
function openTool(id){
 const tool=tools.find(t=>t.id===id);if(!tool||!renderers[id])return;
 $('#ferramentas').classList.add('hidden');$('#modelo').classList.add('hidden');$('#workspace').classList.remove('hidden');
 $('#workspaceContent').innerHTML=`<div class="app-shell"><div class="app-head"><div><span class="eyebrow">${tool.tag.toUpperCase()}</span><h1>${tool.icon} ${tool.name}</h1><p>${tool.desc}</p></div><span class="status"><i></i> Gratuito</span></div><div id="toolBody"></div></div>`;
 try{renderers[id]()}catch(err){console.error(err);$('#toolBody').innerHTML='<div class="result">Não foi possível iniciar esta ferramenta. Recarregue a página.</div>'}
 history.replaceState(null,'',`#${id}`);window.scrollTo({top:0,behavior:'smooth'});
}
function closeTool(){
 if(window.__pomodoroTimer){clearInterval(window.__pomodoroTimer);window.__pomodoroTimer=null}
 $('#workspace').classList.add('hidden');$('#ferramentas').classList.remove('hidden');$('#modelo').classList.remove('hidden');history.replaceState(null,'',location.pathname+location.search);$('#ferramentas').scrollIntoView({behavior:'smooth'});
}

const renderers={
 juros(){
  $('#toolBody').innerHTML=`<div class="form-grid">${field('Valor inicial','jInicial','number','1000','min="0" step="0.01"')}${field('Aporte mensal','jAporte','number','200','min="0" step="0.01"')}${field('Taxa mensal (%)','jTaxa','number','1','min="-99" step="0.01"')}${field('Período (meses)','jMeses','number','60','min="1" max="1200"')}</div><div class="actions"><button class="action" id="jCalc">Calcular projeção</button></div><div class="result" id="jResult"></div>`;
  $('#jCalc').onclick=()=>{const p=Number($('#jInicial').value),a=Number($('#jAporte').value),r=Number($('#jTaxa').value)/100,n=Math.floor(Number($('#jMeses').value));if(![p,a,r,n].every(Number.isFinite)||p<0||a<0||n<1||n>1200||r<=-1)return toast('Confira os valores informados.');let total=p;for(let i=0;i<n;i++)total=total*(1+r)+a;const investido=p+a*n;$('#jResult').innerHTML=`<strong class="big">${money(total)}</strong><p>Total aportado: <b>${money(investido)}</b></p><p>Resultado dos juros: <b>${money(total-investido)}</b></p><p>Projeção matemática; não é garantia de retorno.</p>`};$('#jCalc').click();
 },
 orcamento(){
  const saved=store.get('pl-budget',{income:[],expense:[]});if(!Array.isArray(saved.income))saved.income=[];if(!Array.isArray(saved.expense))saved.expense=[];
  $('#toolBody').innerHTML=`<div class="split"><div><h3>Adicionar movimentação</h3><div class="form-grid">${field('Descrição','bDesc')}${field('Valor','bValue','number','','min="0.01" step="0.01"')}<div class="field"><label for="bType">Tipo</label><select id="bType"><option value="income">Receita</option><option value="expense">Despesa</option></select></div></div><div class="actions"><button id="bAdd" class="action">Adicionar</button><button id="bClear" class="action alt">Limpar tudo</button></div></div><div><h3>Resumo</h3><div class="result" id="bSummary"></div></div></div><div class="task-list" id="bList"></div>`;
  const save=()=>{if(!store.set('pl-budget',saved))toast('Seu navegador bloqueou o armazenamento local.');draw()};
  const draw=()=>{const inc=saved.income.reduce((s,x)=>s+(Number(x.value)||0),0),exp=saved.expense.reduce((s,x)=>s+(Number(x.value)||0),0);$('#bSummary').innerHTML=`<p>Receitas: <b>${money(inc)}</b></p><p>Despesas: <b>${money(exp)}</b></p><strong class="big">${money(inc-exp)}</strong>`;const rows=[...saved.income.map((x,i)=>({...x,type:'income',i})),...saved.expense.map((x,i)=>({...x,type:'expense',i}))];$('#bList').innerHTML=rows.map(x=>`<div class="task"><span>${x.type==='income'?'＋':'−'} ${esc(x.desc)} — <b>${money(x.value)}</b></span><button class="ghost" data-del-budget="${x.type}:${x.i}">Excluir</button></div>`).join('')||'<div class="result">Nenhuma movimentação registrada.</div>';$$('[data-del-budget]').forEach(b=>b.onclick=()=>{const[t,i]=b.dataset.delBudget.split(':');saved[t].splice(Number(i),1);save()})};
  $('#bAdd').onclick=()=>{const desc=$('#bDesc').value.trim(),value=Number($('#bValue').value),type=$('#bType').value;if(!desc||!Number.isFinite(value)||value<=0)return toast('Informe descrição e valor válido.');saved[type].push({desc,value,createdAt:Date.now()});$('#bDesc').value='';$('#bValue').value='';save()};
  $('#bClear').onclick=()=>{if(confirm('Apagar todas as movimentações salvas neste dispositivo?')){saved.income=[];saved.expense=[];save()}};draw();
 },
 curriculo(){
  const draft=store.get('pl-resume',{});
  $('#toolBody').innerHTML=`<div class="split"><div class="form-grid">${field('Nome completo','cName','text',esc(draft.name||''))}${field('Profissão ou objetivo','cTitle','text',esc(draft.title||''))}${field('Telefone','cPhone','tel',esc(draft.phone||''))}${field('E-mail','cEmail','email',esc(draft.email||''))}<div class="field full"><label for="cSummary">Resumo profissional</label><textarea id="cSummary"></textarea></div><div class="field full"><label for="cExperience">Experiência</label><textarea id="cExperience"></textarea></div><div class="field full"><label for="cEducation">Formação e cursos</label><textarea id="cEducation"></textarea></div><div class="field full"><label for="cSkills">Competências</label><textarea id="cSkills"></textarea></div></div><div><div id="resumePreview" class="resume-preview"></div><div class="actions"><button id="cPrint" class="action">Imprimir / salvar PDF</button><button id="cClear" class="action alt">Limpar</button></div></div></div>`;
  ['summary','experience','education','skills'].forEach(k=>$('#c'+k[0].toUpperCase()+k.slice(1)).value=draft[k]||'');
  const data=()=>({name:$('#cName').value,title:$('#cTitle').value,phone:$('#cPhone').value,email:$('#cEmail').value,summary:$('#cSummary').value,experience:$('#cExperience').value,education:$('#cEducation').value,skills:$('#cSkills').value});
  const previewHTML=d=>`<h1>${esc(d.name||'Seu nome')}</h1><p><b>${esc(d.title||'Objetivo profissional')}</b></p><p>${esc(d.phone)} ${d.phone&&d.email?' · ':''}${esc(d.email)}</p><h2>RESUMO</h2><p>${esc(d.summary).replace(/\n/g,'<br>')||'Adicione seu resumo profissional.'}</p><h2>EXPERIÊNCIA</h2><p>${esc(d.experience).replace(/\n/g,'<br>')||'Adicione suas experiências.'}</p><h2>FORMAÇÃO</h2><p>${esc(d.education).replace(/\n/g,'<br>')||'Adicione sua formação.'}</p><h2>COMPETÊNCIAS</h2><p>${esc(d.skills).replace(/\n/g,'<br>')||'Adicione suas competências.'}</p>`;
  const update=()=>{const d=data();$('#resumePreview').innerHTML=previewHTML(d);store.set('pl-resume',d)};$$('input,textarea',$('#toolBody')).forEach(i=>i.addEventListener('input',update));
  $('#cPrint').onclick=()=>{const d=data(),w=window.open('','_blank');if(!w)return toast('Permita pop-ups para gerar o PDF.');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Currículo - ${esc(d.name||'Possível Labs')}</title><style>body{font-family:Arial,sans-serif;max-width:800px;margin:40px auto;padding:0 24px;color:#111;line-height:1.5}h1{margin-bottom:4px}h2{font-size:14px;margin-top:28px;border-bottom:1px solid #bbb;padding-bottom:6px}@media print{body{margin:0 auto}}</style></head><body>${previewHTML(d)}</body></html>`);w.document.close();setTimeout(()=>{w.focus();w.print()},250)};
  $('#cClear').onclick=()=>{if(confirm('Limpar o currículo salvo?')){store.set('pl-resume',{});renderers.curriculo()}};update();
 },
 qr(){
  $('#toolBody').innerHTML=`<div class="split"><div><div class="field"><label for="qText">Conteúdo do QR Code</label><textarea id="qText" placeholder="https://seusite.com"></textarea></div><div class="actions"><button id="qMake" class="action">Gerar QR Code</button><button id="qDownload" class="action alt">Baixar PNG</button></div><p>O QR é gerado localmente quando possível; há fallback externo se a biblioteca não carregar.</p></div><div class="result"><div id="qrcode" style="display:grid;place-items:center;min-height:240px"></div></div></div>`;
  const make=()=>{const text=$('#qText').value.trim();if(!text)return toast('Digite um conteúdo.');const box=$('#qrcode');box.innerHTML='';if(window.QRCode){try{new QRCode(box,{text,width:220,height:220,colorDark:'#07111f',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.H});return}catch(e){console.warn(e)}}const url=`https://api.qrserver.com/v1/create-qr-code/?size=500x500&margin=20&data=${encodeURIComponent(text)}`;box.innerHTML=`<img alt="QR Code gerado" src="${url}" width="220" height="220">`};
  $('#qMake').onclick=make;$('#qDownload').onclick=async()=>{const canvas=$('#qrcode canvas');if(canvas)return download(canvas.toDataURL('image/png'),'qrcode-possivel.png');const img=$('#qrcode img');if(!img)return toast('Gere o QR Code primeiro.');try{const res=await fetch(img.src,{mode:'cors'});if(!res.ok)throw new Error();const blob=await res.blob();const u=URL.createObjectURL(blob);download(u,'qrcode-possivel.png');setTimeout(()=>URL.revokeObjectURL(u),1000)}catch{window.open(img.src,'_blank');toast('QR aberto em nova aba; salve a imagem pelo navegador.')}};
 },
 whatsapp(){
  $('#toolBody').innerHTML=`<div class="form-grid">${field('País + DDD + número','wPhone','tel','','placeholder="5531999999999"')}<div class="field full"><label for="wMessage">Mensagem pronta</label><textarea id="wMessage" placeholder="Olá! Gostaria de saber mais..."></textarea></div></div><div class="actions"><button id="wMake" class="action">Criar link</button></div><div class="result" id="wResult">O link aparecerá aqui.</div>`;
  $('#wMake').onclick=()=>{let phone=$('#wPhone').value.replace(/\D/g,''),msg=$('#wMessage').value;if(phone.length===10||phone.length===11)phone='55'+phone;if(phone.length<12||phone.length>15)return toast('Digite um número válido com DDD e país.');const url=`https://wa.me/${phone}${msg?`?text=${encodeURIComponent(msg)}`:''}`;$('#wResult').innerHTML=`<p style="word-break:break-all">${esc(url)}</p><div class="actions"><button class="action" id="wCopy">Copiar</button><a class="button secondary" target="_blank" rel="noreferrer" href="${url}">Testar link</a></div>`;$('#wCopy').onclick=()=>copy(url)};
 },
 utm(){
  $('#toolBody').innerHTML=`<div class="form-grid">${field('URL de destino','uUrl','url','','placeholder="https://seusite.com"')}${field('Origem (utm_source)','uSource','text','','placeholder="instagram"')}${field('Mídia (utm_medium)','uMedium','text','','placeholder="social"')}${field('Campanha (utm_campaign)','uCampaign','text','','placeholder="lancamento"')}${field('Conteúdo opcional','uContent')}${field('Termo opcional','uTerm')}</div><div class="actions"><button id="uMake" class="action">Montar link rastreável</button></div><div id="uResult" class="result">Seu link rastreável aparecerá aqui.</div>`;
  $('#uMake').onclick=()=>{try{const u=new URL($('#uUrl').value.trim());if(!['http:','https:'].includes(u.protocol))throw new Error();const required=[['utm_source','#uSource'],['utm_medium','#uMedium'],['utm_campaign','#uCampaign']];if(required.some(([,s])=>!$(s).value.trim()))return toast('Preencha origem, mídia e campanha.');[...required,['utm_content','#uContent'],['utm_term','#uTerm']].forEach(([k,s])=>{const v=$(s).value.trim();if(v)u.searchParams.set(k,v)});const url=u.toString();$('#uResult').innerHTML=`<p style="word-break:break-all">${esc(url)}</p><button id="uCopy" class="action">Copiar link</button>`;$('#uCopy').onclick=()=>copy(url)}catch{toast('Digite uma URL completa, incluindo https://')}};
 },
 senha(){
  $('#toolBody').innerHTML=`<div class="form-grid">${field('Quantidade de caracteres','pLength','number','20','min="8" max="128"')}<div class="field"><label>Conjuntos</label><div><label><input id="pUpper" type="checkbox" checked> Maiúsculas</label><br><label><input id="pNumbers" type="checkbox" checked> Números</label><br><label><input id="pSymbols" type="checkbox" checked> Símbolos</label></div></div></div><div class="actions"><button id="pMake" class="action">Gerar senha forte</button><button id="pCopy" class="action alt">Copiar</button></div><div class="result password-output" id="pResult"></div>`;
  const rand=max=>{if(globalThis.crypto&&crypto.getRandomValues){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%max}return Math.floor(Math.random()*max)};
  const generate=()=>{const len=Math.min(128,Math.max(8,Math.floor(Number($('#pLength').value)||20)));let pools=['abcdefghijklmnopqrstuvwxyz'];if($('#pUpper').checked)pools.push('ABCDEFGHIJKLMNOPQRSTUVWXYZ');if($('#pNumbers').checked)pools.push('0123456789');if($('#pSymbols').checked)pools.push('!@#$%&*+-_=?.');const all=pools.join('');let out=pools.map(p=>p[rand(p.length)]);while(out.length<len)out.push(all[rand(all.length)]);for(let i=out.length-1;i>0;i--){const j=rand(i+1);[out[i],out[j]]=[out[j],out[i]]}const pass=out.slice(0,len).join('');$('#pResult').textContent=pass;return pass};$('#pMake').onclick=generate;$('#pCopy').onclick=()=>copy($('#pResult').textContent);generate();
 },
 pomodoro(){
  if(window.__pomodoroTimer)clearInterval(window.__pomodoroTimer);const state=store.get('pl-pomodoro',{count:0,focus:25,break:5});let mode='focus',remaining=(state.focus||25)*60,running=false;
  $('#toolBody').innerHTML=`<div class="form-grid">${field('Foco (min)','timerFocus','number',String(state.focus||25),'min="1" max="180"')}${field('Pausa (min)','timerBreak','number',String(state.break||5),'min="1" max="60"')}</div><div class="timer"><span class="eyebrow" id="timerMode">SESSÃO DE FOCO</span><div class="timer-display" id="timerDisplay">25:00</div><p>Sessões concluídas: <b id="timerCount">${Number(state.count)||0}</b></p><div class="actions" style="justify-content:center"><button id="timerStart" class="action">Iniciar</button><button id="timerReset" class="action alt">Reiniciar</button><button id="timerSwitch" class="action alt">Alternar foco/pausa</button></div></div>`;
  const mins=()=>Math.min(180,Math.max(1,Math.floor(Number(mode==='focus'?$('#timerFocus').value:$('#timerBreak').value)||1)));
  const draw=()=>{$('#timerDisplay').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;$('#timerMode').textContent=mode==='focus'?'SESSÃO DE FOCO':'PAUSA';$('#timerStart').textContent=running?'Pausar':'Iniciar'};
  const persist=()=>store.set('pl-pomodoro',{count:Number($('#timerCount').textContent)||0,focus:Number($('#timerFocus').value)||25,break:Number($('#timerBreak').value)||5});
  const reset=()=>{running=false;clearInterval(window.__pomodoroTimer);window.__pomodoroTimer=null;remaining=mins()*60;draw();persist()};
  const switchMode=()=>{if(mode==='focus'&&remaining===0){$('#timerCount').textContent=(Number($('#timerCount').textContent)||0)+1;toast('Sessão concluída!')}mode=mode==='focus'?'break':'focus';reset()};
  $('#timerStart').onclick=()=>{running=!running;draw();if(running&&!window.__pomodoroTimer){window.__pomodoroTimer=setInterval(()=>{if(!running)return;if(remaining>0){remaining--;draw()}else switchMode()},1000)}else if(!running){clearInterval(window.__pomodoroTimer);window.__pomodoroTimer=null}};$('#timerReset').onclick=reset;$('#timerSwitch').onclick=switchMode;$('#timerFocus').onchange=reset;$('#timerBreak').onchange=reset;draw();
 },
 tarefas(){
  let tasks=store.get('pl-tasks',[]);if(!Array.isArray(tasks))tasks=[];
  $('#toolBody').innerHTML=`<div class="form-grid">${field('Nova tarefa','tText')}<div class="field"><label for="tPriority">Prioridade</label><select id="tPriority"><option>Normal</option><option>Alta</option><option>Baixa</option></select></div></div><div class="actions"><button id="tAdd" class="action">Adicionar tarefa</button><button id="tClearDone" class="action alt">Limpar concluídas</button></div><div class="task-list" id="tList"></div>`;
  const save=()=>{store.set('pl-tasks',tasks);draw()};const draw=()=>{$('#tList').innerHTML=tasks.map((t,i)=>`<div class="task ${t.done?'done':''}"><label><input type="checkbox" data-check-task="${i}" ${t.done?'checked':''}> <span>${esc(t.text)}</span> <small>${esc(t.priority)}</small></label><button class="ghost" data-del-task="${i}">Excluir</button></div>`).join('')||'<div class="result">Nenhuma tarefa ainda.</div>';$$('[data-check-task]').forEach(c=>c.onchange=()=>{tasks[Number(c.dataset.checkTask)].done=c.checked;save()});$$('[data-del-task]').forEach(b=>b.onclick=()=>{tasks.splice(Number(b.dataset.delTask),1);save()})};
  $('#tAdd').onclick=()=>{const text=$('#tText').value.trim();if(!text)return toast('Digite uma tarefa.');tasks.unshift({text,priority:$('#tPriority').value,done:false,createdAt:Date.now()});$('#tText').value='';save()};$('#tText').onkeydown=e=>{if(e.key==='Enter')$('#tAdd').click()};$('#tClearDone').onclick=()=>{tasks=tasks.filter(t=>!t.done);save()};draw();
 },
 imagem(){
  $('#toolBody').innerHTML=`<div class="form-grid"><div class="field full"><label for="iFile">Escolha uma imagem</label><input id="iFile" type="file" accept="image/*"></div><div class="field"><label for="iFormat">Formato de saída</label><select id="iFormat"><option value="image/png">PNG</option><option value="image/jpeg">JPEG</option><option value="image/webp">WebP</option></select></div><div class="field"><label for="iQuality">Qualidade JPEG/WebP</label><input id="iQuality" type="range" min="10" max="100" value="90"><span id="iQualityLabel">90%</span></div></div><div class="actions"><button id="iConvert" class="action">Converter e baixar</button></div><div class="result" id="iPreview">A imagem é processada no seu dispositivo.</div>`;
  let loaded=null;$('#iQuality').oninput=()=>$('#iQualityLabel').textContent=$('#iQuality').value+'%';$('#iFile').onchange=()=>{const file=$('#iFile').files[0];loaded=null;if(!file)return;if(!file.type.startsWith('image/'))return toast('Escolha um arquivo de imagem.');if(file.size>25*1024*1024)return toast('Use uma imagem de até 25 MB.');const reader=new FileReader();reader.onerror=()=>toast('Não foi possível ler a imagem.');reader.onload=()=>{const img=new Image();img.onerror=()=>toast('Arquivo de imagem inválido.');img.onload=()=>{loaded={img,file};$('#iPreview').innerHTML=`<img src="${reader.result}" alt="Prévia" style="max-width:100%;max-height:320px;border-radius:12px"><p>${esc(file.name)} — ${img.naturalWidth}×${img.naturalHeight}</p>`};img.src=reader.result};reader.readAsDataURL(file)};
  $('#iConvert').onclick=()=>{if(!loaded)return toast('Escolha uma imagem primeiro.');const {img,file}=loaded,canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;const ctx=canvas.getContext('2d');if(!ctx)return toast('Seu navegador não suporta conversão em canvas.');const type=$('#iFormat').value;if(type==='image/jpeg'){ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height)}ctx.drawImage(img,0,0);canvas.toBlob(blob=>{if(!blob)return toast('Este formato não é suportado pelo navegador.');const ext=type==='image/png'?'png':type==='image/jpeg'?'jpg':'webp',u=URL.createObjectURL(blob);download(u,`${file.name.replace(/\.[^.]+$/,'')}.${ext}`);setTimeout(()=>URL.revokeObjectURL(u),1000);toast('Conversão concluída.')},type,Number($('#iQuality').value)/100)};
 }
};

function init(){renderGrid();$('#searchTools').addEventListener('input',e=>renderGrid(e.target.value));$('#closeWorkspace').onclick=closeTool;const savedTheme=localStorage.getItem('pl-theme');if(savedTheme==='light')document.documentElement.classList.add('light');$('#themeToggle').onclick=()=>{document.documentElement.classList.toggle('light');try{localStorage.setItem('pl-theme',document.documentElement.classList.contains('light')?'light':'dark')}catch{}};const id=location.hash.slice(1);if(tools.some(t=>t.id===id))openTool(id);window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if(tools.some(t=>t.id===next))openTool(next);else if(!location.hash&&!$('#workspace').classList.contains('hidden'))closeTool()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();