const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const toast=msg=>{const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2200)};
const copy=async text=>{try{await navigator.clipboard.writeText(text);toast('Copiado para a área de transferência.')}catch{toast('Não foi possível copiar.')}};

const tools=[
{id:'juros',icon:'📈',name:'Juros Compostos',tag:'Finanças',desc:'Projete patrimônio, aportes e crescimento ao longo do tempo.'},
{id:'orcamento',icon:'💰',name:'Orçamento Pessoal',tag:'Finanças',desc:'Organize receitas e despesas e descubra sua sobra mensal.'},
{id:'curriculo',icon:'📄',name:'Currículo Rápido',tag:'Carreira',desc:'Monte um currículo limpo e pronto para imprimir em minutos.'},
{id:'qr',icon:'▦',name:'QR Code Pro',tag:'Marketing',desc:'Transforme links, textos e contatos em QR Codes baixáveis.'},
{id:'whatsapp',icon:'💬',name:'Link para WhatsApp',tag:'Vendas',desc:'Crie links com mensagem pronta para atendimento e campanhas.'},
{id:'utm',icon:'🔗',name:'Construtor de UTM',tag:'Marketing',desc:'Adicione rastreamento profissional aos links de campanha.'},
{id:'senha',icon:'🔐',name:'Gerador de Senhas',tag:'Segurança',desc:'Gere senhas fortes localmente sem enviar dados para servidores.'},
{id:'pomodoro',icon:'⏱️',name:'Pomodoro Focus',tag:'Produtividade',desc:'Cronômetro de foco com ciclos, pausas e contagem de sessões.'},
{id:'tarefas',icon:'✅',name:'Planejador de Tarefas',tag:'Produtividade',desc:'Registre prioridades e acompanhe tarefas salvas no dispositivo.'},
{id:'imagem',icon:'🖼️',name:'Conversor de Imagem',tag:'Utilidade',desc:'Converta imagens para PNG, JPEG ou WebP direto no navegador.'}
];

function renderGrid(filter=''){
 const q=filter.trim().toLowerCase();
 $('#toolGrid').innerHTML=tools.filter(t=>`${t.name} ${t.tag} ${t.desc}`.toLowerCase().includes(q)).map(t=>`<article class="tool-card"><span class="tool-icon">${t.icon}</span><h3>${t.name}</h3><p>${t.desc}</p><div class="tool-meta"><span>${t.tag}</span><button data-open="${t.id}">Abrir →</button></div></article>`).join('')||'<p>Nenhuma ferramenta encontrada.</p>';
 $$('[data-open]').forEach(b=>b.onclick=()=>openTool(b.dataset.open));
}
function openTool(id){
 const tool=tools.find(t=>t.id===id);if(!tool)return;
 $('#ferramentas').classList.add('hidden');$('#modelo').classList.add('hidden');$('#workspace').classList.remove('hidden');
 $('#workspaceContent').innerHTML=`<div class="app-shell"><div class="app-head"><div><span class="eyebrow">${tool.tag.toUpperCase()}</span><h1>${tool.icon} ${tool.name}</h1><p>${tool.desc}</p></div><span class="status"><i></i> Gratuito</span></div><div id="toolBody"></div></div>`;
 renderers[id]();location.hash=id;scrollTo({top:0,behavior:'smooth'});
}
function closeTool(){
 $('#workspace').classList.add('hidden');$('#ferramentas').classList.remove('hidden');$('#modelo').classList.remove('hidden');history.replaceState(null,'',location.pathname);$('#ferramentas').scrollIntoView({behavior:'smooth'});
}
const field=(label,id,type='text',value='',extra='')=>`<div class="field"><label for="${id}">${label}</label><input id="${id}" type="${type}" value="${value}" ${extra}></div>`;

const renderers={
 juros(){
  $('#toolBody').innerHTML=`<div class="form-grid">${field('Valor inicial','jInicial','number','1000','min="0" step="0.01"')}${field('Aporte mensal','jAporte','number','200','min="0" step="0.01"')}${field('Taxa mensal (%)','jTaxa','number','1','step="0.01"')}${field('Período (meses)','jMeses','number','60','min="1"')}</div><div class="actions"><button class="action" id="jCalc">Calcular projeção</button></div><div class="result" id="jResult">Preencha os valores para projetar o crescimento.</div>`;
  $('#jCalc').onclick=()=>{let p=+$(' #jInicial'.trim()).value,a=+$('#jAporte').value,r=+$('#jTaxa').value/100,n=Math.max(1,+$('#jMeses').value),total=p;for(let i=0;i<n;i++)total=total*(1+r)+a;const investido=p+a*n,juros=total-investido;$('#jResult').innerHTML=`<strong class="big">${money(total)}</strong><p>Total investido: <b>${money(investido)}</b></p><p>Rendimento estimado: <b>${money(juros)}</b></p><p>Projeção matemática; não é garantia de retorno.</p>`};$('#jCalc').click();
 },
 orcamento(){
  const saved=JSON.parse(localStorage.getItem('pl-budget')||'{"income":[],"expense":[]}');
  $('#toolBody').innerHTML=`<div class="split"><div><h3>Adicionar movimentação</h3><div class="form-grid">${field('Descrição','bDesc')}${field('Valor','bValue','number','','min="0" step="0.01"')}<div class="field"><label>Tipo</label><select id="bType"><option value="income">Receita</option><option value="expense">Despesa</option></select></div></div><div class="actions"><button id="bAdd" class="action">Adicionar</button><button id="bClear" class="action alt">Limpar tudo</button></div></div><div><h3>Resumo mensal</h3><div class="result" id="bSummary"></div></div></div><div class="task-list" id="bList"></div>`;
  const draw=()=>{const inc=saved.income.reduce((s,x)=>s+x.value,0),exp=saved.expense.reduce((s,x)=>s+x.value,0);$('#bSummary').innerHTML=`<p>Receitas: <b>${money(inc)}</b></p><p>Despesas: <b>${money(exp)}</b></p><strong class="big">${money(inc-exp)}</strong>`;$('#bList').innerHTML=[...saved.income.map((x,i)=>({...x,type:'income',i})),...saved.expense.map((x,i)=>({...x,type:'expense',i}))].map(x=>`<div class="task"><span>${x.type==='income'?'＋':'−'} ${esc(x.desc)} — <b>${money(x.value)}</b></span><button class="ghost" data-del-budget="${x.type}:${x.i}">Excluir</button></div>`).join('');$$('[data-del-budget]').forEach(b=>b.onclick=()=>{const[t,i]=b.dataset.delBudget.split(':');saved[t].splice(+i,1);save()})};
  const save=()=>{localStorage.setItem('pl-budget',JSON.stringify(saved));draw()};$('#bAdd').onclick=()=>{const desc=$('#bDesc').value.trim(),value=+$('#bValue').value,type=$('#bType').value;if(!desc||value<=0)return toast('Informe descrição e valor.');saved[type].push({desc,value});$('#bDesc').value='';$('#bValue').value='';save()};$('#bClear').onclick=()=>{saved.income=[];saved.expense=[];save()};draw();
 },
 curriculo(){
  $('#toolBody').innerHTML=`<div class="split"><div class="form-grid">${field('Nome completo','cName')}${field('Profissão ou objetivo','cTitle')}${field('Telefone','cPhone','tel')}${field('E-mail','cEmail','email')}<div class="field full"><label>Resumo profissional</label><textarea id="cSummary" placeholder="Quem você é, seus pontos fortes e objetivo."></textarea></div><div class="field full"><label>Experiência</label><textarea id="cExperience" placeholder="Empresa — função — período — principais resultados"></textarea></div><div class="field full"><label>Formação e cursos</label><textarea id="cEducation"></textarea></div><div class="field full"><label>Competências</label><textarea id="cSkills" placeholder="Atendimento, vendas, Excel..."></textarea></div></div><div><div id="resumePreview" class="resume-preview"><p>Preencha os campos para visualizar.</p></div><div class="actions"><button id="cPrint" class="action">Imprimir / salvar PDF</button></div></div></div>`;
  const update=()=>{$('#resumePreview').innerHTML=`<h1>${esc($('#cName').value||'Seu nome')}</h1><p><b>${esc($('#cTitle').value||'Objetivo profissional')}</b></p><p>${esc($('#cPhone').value)} ${$('#cPhone').value&&$('#cEmail').value?' · ':''}${esc($('#cEmail').value)}</p><h2>RESUMO</h2><p>${esc($('#cSummary').value).replace(/\n/g,'<br>')||'Adicione seu resumo profissional.'}</p><h2>EXPERIÊNCIA</h2><p>${esc($('#cExperience').value).replace(/\n/g,'<br>')||'Adicione suas experiências.'}</p><h2>FORMAÇÃO</h2><p>${esc($('#cEducation').value).replace(/\n/g,'<br>')||'Adicione sua formação.'}</p><h2>COMPETÊNCIAS</h2><p>${esc($('#cSkills').value).replace(/\n/g,'<br>')||'Adicione suas competências.'}</p>`};$$('input,textarea',$('#toolBody')).forEach(i=>i.oninput=update);$('#cPrint').onclick=()=>print();update();
 },
 qr(){
  $('#toolBody').innerHTML=`<div class="split"><div><div class="field"><label>Conteúdo do QR Code</label><textarea id="qText" placeholder="https://seusite.com"></textarea></div><div class="actions"><button id="qMake" class="action">Gerar QR Code</button><button id="qDownload" class="action alt">Baixar PNG</button></div></div><div class="result"><div id="qrcode" style="display:grid;place-items:center;min-height:240px"></div></div></div>`;
  const make=()=>{const text=$('#qText').value.trim();if(!text)return toast('Digite um conteúdo.');$('#qrcode').innerHTML='';if(!window.QRCode)return toast('Biblioteca de QR Code não carregou.');new QRCode($('#qrcode'),{text,width:220,height:220,colorDark:'#07111f',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.H})};$('#qMake').onclick=make;$('#qDownload').onclick=()=>{const img=$('#qrcode img')||$('#qrcode canvas');if(!img)return toast('Gere o QR Code primeiro.');const a=document.createElement('a');a.download='qrcode-possivel.png';a.href=img.tagName==='CANVAS'?img.toDataURL('image/png'):img.src;a.click()};
 },
 whatsapp(){
  $('#toolBody').innerHTML=`<div class="form-grid">${field('DDD + número','wPhone','tel','','placeholder="5531999999999"')}<div class="field full"><label>Mensagem pronta</label><textarea id="wMessage" placeholder="Olá! Gostaria de saber mais..."></textarea></div></div><div class="actions"><button id="wMake" class="action">Criar link</button></div><div class="result" id="wResult">O link aparecerá aqui.</div>`;
  $('#wMake').onclick=()=>{const phone=$('#wPhone').value.replace(/\D/g,''),msg=$('#wMessage').value;if(phone.length<10)return toast('Digite um número válido com DDD.');const url=`https://wa.me/${phone}?text=${encodeURIComponent(msg)}`;$('#wResult').innerHTML=`<p>${esc(url)}</p><div class="actions"><button class="action" id="wCopy">Copiar</button><a class="button secondary" target="_blank" rel="noreferrer" href="${url}">Testar link</a></div>`;$('#wCopy').onclick=()=>copy(url)};
 },
 utm(){
  $('#toolBody').innerHTML=`<div class="form-grid">${field('URL de destino','uUrl','url','','placeholder="https://seusite.com"')}${field('Origem (utm_source)','uSource','text','','placeholder="instagram"')}${field('Mídia (utm_medium)','uMedium','text','','placeholder="social"')}${field('Campanha (utm_campaign)','uCampaign','text','','placeholder="lancamento"')}${field('Conteúdo opcional','uContent')}${field('Termo opcional','uTerm')}</div><div class="actions"><button id="uMake" class="action">Montar link rastreável</button></div><div id="uResult" class="result">Seu link rastreável aparecerá aqui.</div>`;
  $('#uMake').onclick=()=>{try{const u=new URL($('#uUrl').value);[['utm_source','#uSource'],['utm_medium','#uMedium'],['utm_campaign','#uCampaign'],['utm_content','#uContent'],['utm_term','#uTerm']].forEach(([k,s])=>{const v=$(s).value.trim();if(v)u.searchParams.set(k,v)});const url=u.toString();$('#uResult').innerHTML=`<p>${esc(url)}</p><button id="uCopy" class="action">Copiar link</button>`;$('#uCopy').onclick=()=>copy(url)}catch{toast('Digite uma URL completa, incluindo https://')}};
 },
 senha(){
  $('#toolBody').innerHTML=`<div class="form-grid">${field('Quantidade de caracteres','pLength','number','20','min="8" max="128"')}<div class="field"><label>Conjuntos</label><div><label><input id="pUpper" type="checkbox" checked> Maiúsculas</label><br><label><input id="pNumbers" type="checkbox" checked> Números</label><br><label><input id="pSymbols" type="checkbox" checked> Símbolos</label></div></div></div><div class="actions"><button id="pMake" class="action">Gerar senha forte</button><button id="pCopy" class="action alt">Copiar</button></div><div class="result password-output" id="pResult">Clique em gerar.</div>`;
  const generate=()=>{const len=Math.min(128,Math.max(8,+$('#pLength').value||20));let chars='abcdefghijklmnopqrstuvwxyz';if($('#pUpper').checked)chars+='ABCDEFGHIJKLMNOPQRSTUVWXYZ';if($('#pNumbers').checked)chars+='0123456789';if($('#pSymbols').checked)chars+='!@#$%&*+-_=?.';const arr=new Uint32Array(len);crypto.getRandomValues(arr);const pass=[...arr].map(n=>chars[n%chars.length]).join('');$('#pResult').textContent=pass;return pass};$('#pMake').onclick=generate;$('#pCopy').onclick=()=>copy($('#pResult').textContent);generate();
 },
 pomodoro(){
  $('#toolBody').innerHTML=`<div class="timer"><div><span class="eyebrow" id="timerMode">SESSÃO DE FOCO</span><div class="timer-display" id="timerDisplay">25:00</div><p>Sessões concluídas: <b id="timerCount">${localStorage.getItem('pl-pomodoro-count')||0}</b></p><div class="actions" style="justify-content:center"><button id="timerStart" class="action">Iniciar</button><button id="timerReset" class="action alt">Reiniciar</button><button id="timerSwitch" class="action alt">Alternar foco/pausa</button></div></div></div>`;
  let focus=true,left=25*60,timer=null;const draw=()=>{$('#timerDisplay').textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;document.title=`${$('#timerDisplay').textContent} — Possível Labs`};const stop=()=>{clearInterval(timer);timer=null;$('#timerStart').textContent='Iniciar'};const reset=()=>{stop();left=(focus?25:5)*60;draw()};$('#timerStart').onclick=()=>{if(timer)return stop();$('#timerStart').textContent='Pausar';timer=setInterval(()=>{left--;draw();if(left<=0){stop();if(focus){const c=+(localStorage.getItem('pl-pomodoro-count')||0)+1;localStorage.setItem('pl-pomodoro-count',c);$('#timerCount').textContent=c}toast(focus?'Foco concluído. Hora da pausa!':'Pausa concluída. Volte ao foco!');focus=!focus;$('#timerMode').textContent=focus?'SESSÃO DE FOCO':'PAUSA';reset()}},1000)};$('#timerReset').onclick=reset;$('#timerSwitch').onclick=()=>{focus=!focus;$('#timerMode').textContent=focus?'SESSÃO DE FOCO':'PAUSA';reset()};draw();
 },
 tarefas(){
  let tasks=JSON.parse(localStorage.getItem('pl-tasks')||'[]');$('#toolBody').innerHTML=`<div class="form-grid">${field('Nova tarefa','tText')}<div class="field"><label>Prioridade</label><select id="tPriority"><option>Alta</option><option selected>Média</option><option>Baixa</option></select></div></div><div class="actions"><button id="tAdd" class="action">Adicionar tarefa</button><button id="tClear" class="action alt">Excluir concluídas</button></div><div class="task-list" id="tList"></div>`;
  const save=()=>{localStorage.setItem('pl-tasks',JSON.stringify(tasks));draw()};const draw=()=>{$('#tList').innerHTML=tasks.map((t,i)=>`<div class="task ${t.done?'done':''}"><label><input type="checkbox" data-check="${i}" ${t.done?'checked':''}> <span>${esc(t.text)}</span> <small>(${t.priority})</small></label><button class="ghost" data-delete="${i}">Excluir</button></div>`).join('')||'<div class="result">Nenhuma tarefa cadastrada.</div>';$$('[data-check]').forEach(x=>x.onchange=()=>{tasks[+x.dataset.check].done=x.checked;save()});$$('[data-delete]').forEach(x=>x.onclick=()=>{tasks.splice(+x.dataset.delete,1);save()})};$('#tAdd').onclick=()=>{const text=$('#tText').value.trim();if(!text)return toast('Digite uma tarefa.');tasks.push({text,priority:$('#tPriority').value,done:false});$('#tText').value='';save()};$('#tClear').onclick=()=>{tasks=tasks.filter(t=>!t.done);save()};draw();
 },
 imagem(){
  $('#toolBody').innerHTML=`<div class="split"><div><div class="field"><label>Escolha uma imagem</label><input id="iFile" type="file" accept="image/*"></div><div class="field"><label>Formato de saída</label><select id="iFormat"><option value="image/png">PNG</option><option value="image/jpeg">JPEG</option><option value="image/webp">WebP</option></select></div><div class="field"><label>Qualidade (JPEG/WebP)</label><input id="iQuality" type="range" min="0.2" max="1" step="0.05" value="0.9"></div><div class="actions"><button id="iConvert" class="action">Converter e baixar</button></div></div><div class="result" id="iPreview">A prévia aparecerá aqui.</div></div>`;
  let img=null;$('#iFile').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{img=new Image();img.onload=()=>{$('#iPreview').innerHTML=`<img src="${reader.result}" alt="Prévia" style="max-width:100%;max-height:360px;border-radius:12px"><p>${img.width} × ${img.height}px</p>`};img.src=reader.result};reader.readAsDataURL(file)};$('#iConvert').onclick=()=>{if(!img)return toast('Escolha uma imagem primeiro.');const canvas=document.createElement('canvas');canvas.width=img.width;canvas.height=img.height;canvas.getContext('2d').drawImage(img,0,0);const type=$('#iFormat').value,ext=type.split('/')[1].replace('jpeg','jpg');const a=document.createElement('a');a.download=`imagem-convertida.${ext}`;a.href=canvas.toDataURL(type,+$('#iQuality').value);a.click()};
 }
};

$('#searchTools').oninput=e=>renderGrid(e.target.value);$('#closeWorkspace').onclick=closeTool;$('#themeToggle').onclick=()=>{document.documentElement.classList.toggle('light');localStorage.setItem('pl-theme',document.documentElement.classList.contains('light')?'light':'dark')};if(localStorage.getItem('pl-theme')==='light')document.documentElement.classList.add('light');
renderGrid();
const initial=location.hash.slice(1);if(tools.some(t=>t.id===initial))openTool(initial);
