create table if not exists public.subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, plan text not null check (plan in ('free','pro')), status text not null check (status in ('pending','active','past_due','grace_period','canceled','expired')), provider text not null default 'mercadopago', provider_customer_id text, provider_subscription_id text unique, current_period_start timestamptz, current_period_end timestamptz, cancel_at_period_end boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists subscriptions_user_status_idx on public.subscriptions(user_id,status);
alter table public.subscriptions enable row level security;
create policy "Usuários leem suas assinaturas" on public.subscriptions for select using (auth.uid()=user_id);

create table if not exists public.plan_entitlements (id bigint generated by default as identity primary key, plan text not null check (plan in ('free','pro')), feature_key text not null, enabled boolean not null default true, numeric_limit numeric, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(plan,feature_key));
alter table public.plan_entitlements enable row level security;
create policy "Entitlements são públicos para usuários autenticados" on public.plan_entitlements for select using (auth.role()='authenticated');

create table if not exists public.usage_counters (id bigint generated by default as identity primary key, user_id uuid not null references public.profiles(id) on delete cascade, feature_key text not null, period text not null, usage numeric not null default 0, updated_at timestamptz not null default now(), unique(user_id,feature_key,period));
alter table public.usage_counters enable row level security;
create policy "Usuários leem seu uso" on public.usage_counters for select using (auth.uid()=user_id);

create table if not exists public.payment_webhook_events (id uuid primary key default gen_random_uuid(), provider text not null, event_id text not null, event_type text not null, payload jsonb not null, processed_at timestamptz, created_at timestamptz not null default now(), unique(provider,event_id));
alter table public.payment_webhook_events enable row level security;

create table if not exists public.feature_audit_logs (id bigint generated by default as identity primary key, user_id uuid references public.profiles(id) on delete set null, feature_key text not null, action text not null, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
alter table public.feature_audit_logs enable row level security;

alter table public.listings add column if not exists category text;
alter table public.listings add column if not exists images text[] not null default '{}';
alter table public.listings drop constraint if exists listings_listing_type_check;
alter table public.listings add constraint listings_listing_type_check check (listing_type in ('venda','troca','doacao'));
alter table public.listings drop constraint if exists listings_status_check;
alter table public.listings add constraint listings_status_check check (status in ('active','reserved','completed','paused','sold','closed'));

insert into public.plan_entitlements(plan,feature_key,enabled,numeric_limit) values
('free','active_listings',true,5),('pro','active_listings',true,50),('free','storage_gb',true,1),('pro','storage_gb',true,10),('free','call_participants',true,4),('pro','call_participants',true,12),('free','call_duration_minutes',true,30),('pro','call_duration_minutes',true,120),('free','advanced_stats',false,null),('pro','advanced_stats',true,null),('free','scheduled_posts',false,null),('pro','scheduled_posts',true,null),('free','saved_searches',false,null),('pro','saved_searches',true,null)
on conflict(plan,feature_key) do update set enabled=excluded.enabled,numeric_limit=excluded.numeric_limit;

create or replace function public.get_effective_plan(p_user_id uuid) returns text language sql security definer set search_path=public as $$ select coalesce((select plan from public.subscriptions where user_id=p_user_id and status in ('active','grace_period') and (current_period_end is null or current_period_end>now()) order by created_at desc limit 1),'free') $$;
create or replace function public.can_use_feature(p_user_id uuid,p_feature_key text) returns boolean language sql security definer set search_path=public as $$ select coalesce((select enabled from public.plan_entitlements where plan=public.get_effective_plan(p_user_id) and feature_key=p_feature_key),false) $$;
create or replace function public.get_user_entitlements(p_user_id uuid) returns table(feature_key text, enabled boolean, numeric_limit numeric) language sql security definer set search_path=public as $$ select feature_key,enabled,numeric_limit from public.plan_entitlements where plan=public.get_effective_plan(p_user_id) $$;
create or replace function public.check_plan_limit(p_user_id uuid,p_feature_key text) returns boolean language plpgsql security definer set search_path=public as $$ declare v_limit numeric; v_usage numeric; begin select numeric_limit into v_limit from public.plan_entitlements where plan=public.get_effective_plan(p_user_id) and feature_key=p_feature_key; if v_limit is null then return public.can_use_feature(p_user_id,p_feature_key); end if; if p_feature_key='active_listings' then select count(*) into v_usage from public.listings where seller_id=p_user_id and status='active'; else select coalesce(sum(usage),0) into v_usage from public.usage_counters where user_id=p_user_id and feature_key=p_feature_key; end if; return v_usage < v_limit; end $$;
